server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/danitherev-coder/microservicios
          username: danitherev-coder
          password: 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
          search-paths: config-data
  application:
    name: config-service